/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/15/2017
Description:	Creates the UserRole table and respective stored procedures

*/


USE opendevtools;



-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `opendevtools`.`UserRole` (
id INT AUTO_INCREMENT,
name VARCHAR(255),
description VARCHAR(511),
CONSTRAINT pk_UserRole_id PRIMARY KEY (id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_Load`
(
	 IN paramid INT
)
BEGIN
	SELECT
		`UserRole`.`id` AS `id`,
		`UserRole`.`name` AS `name`,
		`UserRole`.`description` AS `description`
	FROM `UserRole`
	WHERE 		`UserRole`.`id` = paramid;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_LoadAll`()
BEGIN
	SELECT
		`UserRole`.`id` AS `id`,
		`UserRole`.`name` AS `name`,
		`UserRole`.`description` AS `description`
	FROM `UserRole`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_Add`
(
	 IN paramname VARCHAR(255),
	 IN paramdescription VARCHAR(511)
)
BEGIN
	INSERT INTO `UserRole` (name,description)
	VALUES (paramname, paramdescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_Update`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(511)
)
BEGIN
	UPDATE `UserRole`
	SET name = paramname
		,description = paramdescription
	WHERE		`UserRole`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_Delete`
(
	IN paramid INT
)
BEGIN
	DELETE FROM `UserRole`
	WHERE		`UserRole`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_UserRole_Search`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(511)
)
BEGIN
	SELECT
		`UserRole`.`id` AS `id`,
		`UserRole`.`name` AS `name`,
		`UserRole`.`description` AS `description`
	FROM `UserRole`
	WHERE
		COALESCE(UserRole.`id`,0) = COALESCE(paramid,UserRole.`id`,0)
		AND COALESCE(UserRole.`name`,'') = COALESCE(paramname,UserRole.`name`,'')
		AND COALESCE(UserRole.`description`,'') = COALESCE(paramdescription,UserRole.`description`,'');
END //
DELIMITER ;


