/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/19/2017
Description:	Creates the ForumCategory table and respective stored procedures

*/


USE opendevtools;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `opendevtools`.`ForumCategory`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_Load`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_LoadAll`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_Add`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_Update`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_Delete`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumCategory_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `opendevtools`.`ForumCategory` (
id INT AUTO_INCREMENT,
name VARCHAR(255),
description VARCHAR(512),
CONSTRAINT pk_ForumCategory_id PRIMARY KEY (id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_Load`
(
	 IN paramid INT
)
BEGIN
	SELECT
		`ForumCategory`.`id` AS `id`,
		`ForumCategory`.`name` AS `name`,
		`ForumCategory`.`description` AS `description`
	FROM `ForumCategory`
	WHERE 		`ForumCategory`.`id` = paramid;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_LoadAll`
()
BEGIN
	SELECT
		`ForumCategory`.`id` AS `id`,
		`ForumCategory`.`name` AS `name`,
		`ForumCategory`.`description` AS `description`
	FROM `ForumCategory`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_Add`
(
	 IN paramname VARCHAR(255),
	 IN paramdescription VARCHAR(512)
)
BEGIN
	INSERT INTO `ForumCategory` (name,description)
	VALUES (paramname, paramdescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_Update`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(512)
)
BEGIN
	UPDATE `ForumCategory`
	SET name = paramname
		,description = paramdescription
	WHERE		`ForumCategory`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_Delete`
(
	IN paramid INT
)
BEGIN
	DELETE FROM `ForumCategory`
	WHERE		`ForumCategory`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumCategory_Search`
(
	IN paramid INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(512)
)
BEGIN
	SELECT
		`ForumCategory`.`id` AS `id`,
		`ForumCategory`.`name` AS `name`,
		`ForumCategory`.`description` AS `description`
	FROM `ForumCategory`
	WHERE
		COALESCE(ForumCategory.`id`,0) = COALESCE(paramid,ForumCategory.`id`,0)
		AND COALESCE(ForumCategory.`name`,'') = COALESCE(paramname,ForumCategory.`name`,'')
		AND COALESCE(ForumCategory.`description`,'') = COALESCE(paramdescription,ForumCategory.`description`,'');
END //
DELIMITER ;


