/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/19/2017
Description:	Creates the Forum table and respective stored procedures

*/


USE opendevtools;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `opendevtools`.`Forum`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_Load`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_LoadAll`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_Add`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_Update`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_Delete`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_Forum_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `opendevtools`.`Forum` (
id INT AUTO_INCREMENT,
createdByUserId INT,
title VARCHAR(255),
content VARCHAR(32768),
createDate DATETIME,
forumCategoryId INT,
Views INT,
CONSTRAINT pk_Forum_id PRIMARY KEY (id),
CONSTRAINT fk_Forum_createdByUserId_User_id FOREIGN KEY (createdByUserId) REFERENCES User (id),
CONSTRAINT fk_Forum_forumCategoryId_ForumCategory_id FOREIGN KEY (forumCategoryId) REFERENCES ForumCategory (id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_Load`
(
	 IN paramid INT
)
BEGIN
	SELECT
		`Forum`.`id` AS `id`,
		`Forum`.`createdByUserId` AS `createdByUserId`,
		`Forum`.`title` AS `title`,
		`Forum`.`content` AS `content`,
		`Forum`.`createDate` AS `createDate`,
		`Forum`.`forumCategoryId` AS `forumCategoryId`,
		`Forum`.`Views` AS `Views`
	FROM `Forum`
	WHERE 		`Forum`.`id` = paramid;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_LoadAll`
()
BEGIN
	SELECT
		`Forum`.`id` AS `id`,
		`Forum`.`createdByUserId` AS `createdByUserId`,
		`Forum`.`title` AS `title`,
		`Forum`.`content` AS `content`,
		`Forum`.`createDate` AS `createDate`,
		`Forum`.`forumCategoryId` AS `forumCategoryId`,
		`Forum`.`Views` AS `Views`
	FROM `Forum`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_Add`
(
	 IN paramcreatedByUserId INT,
	 IN paramtitle VARCHAR(255),
	 IN paramcontent VARCHAR(32768),
	 IN paramcreateDate DATETIME,
	 IN paramforumCategoryId INT,
	 IN paramViews INT
)
BEGIN
	INSERT INTO `Forum` (createdByUserId,title,content,createDate,forumCategoryId,Views)
	VALUES (paramcreatedByUserId, paramtitle, paramcontent, paramcreateDate, paramforumCategoryId, paramViews);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_Update`
(
	IN paramid INT,
	IN paramcreatedByUserId INT,
	IN paramtitle VARCHAR(255),
	IN paramcontent VARCHAR(32768),
	IN paramcreateDate DATETIME,
	IN paramforumCategoryId INT,
	IN paramViews INT
)
BEGIN
	UPDATE `Forum`
	SET createdByUserId = paramcreatedByUserId
		,title = paramtitle
		,content = paramcontent
		,createDate = paramcreateDate
		,forumCategoryId = paramforumCategoryId
		,Views = paramViews
	WHERE		`Forum`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_Delete`
(
	IN paramid INT
)
BEGIN
	DELETE FROM `Forum`
	WHERE		`Forum`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Forum_Search`
(
	IN paramid INT,
	IN paramcreatedByUserId INT,
	IN paramtitle VARCHAR(255),
	IN paramcontent VARCHAR(32768),
	IN paramcreateDate DATETIME,
	IN paramforumCategoryId INT,
	IN paramViews INT
)
BEGIN
	SELECT
		`Forum`.`id` AS `id`,
		`Forum`.`createdByUserId` AS `createdByUserId`,
		`Forum`.`title` AS `title`,
		`Forum`.`content` AS `content`,
		`Forum`.`createDate` AS `createDate`,
		`Forum`.`forumCategoryId` AS `forumCategoryId`,
		`Forum`.`Views` AS `Views`
	FROM `Forum`
	WHERE
		COALESCE(Forum.`id`,0) = COALESCE(paramid,Forum.`id`,0)
		AND COALESCE(Forum.`createdByUserId`,0) = COALESCE(paramcreatedByUserId,Forum.`createdByUserId`,0)
		AND COALESCE(Forum.`title`,'') = COALESCE(paramtitle,Forum.`title`,'')
		AND COALESCE(Forum.`content`,'') = COALESCE(paramcontent,Forum.`content`,'')
		AND COALESCE(CAST(Forum.`createDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramcreateDate AS DATE),CAST(Forum.`createDate` AS DATE), CAST(NOW() AS DATE))
		AND COALESCE(Forum.`forumCategoryId`,0) = COALESCE(paramforumCategoryId,Forum.`forumCategoryId`,0)
		AND COALESCE(Forum.`Views`,0) = COALESCE(paramViews,Forum.`Views`,0);
END //
DELIMITER ;


