/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/19/2017
Description:	Creates the ForumComment table and respective stored procedures

*/


USE opendevtools;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `opendevtools`.`ForumComment`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_Load`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_LoadAll`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_Add`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_Update`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_Delete`;
DROP PROCEDURE IF EXISTS `opendevtools`.`usp_ForumComment_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `opendevtools`.`ForumComment` (
id INT AUTO_INCREMENT,
forumId INT,
userId INT,
comment VARCHAR(32768),
createDate DATETIME,
CONSTRAINT pk_ForumComment_id PRIMARY KEY (id),
CONSTRAINT fk_ForumComment_forumId_Forum_id FOREIGN KEY (forumId) REFERENCES Forum (id),
CONSTRAINT fk_ForumComment_userId_User_id FOREIGN KEY (userId) REFERENCES User (id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_Load`
(
	 IN paramid INT
)
BEGIN
	SELECT
		`ForumComment`.`id` AS `id`,
		`ForumComment`.`forumId` AS `forumId`,
		`ForumComment`.`userId` AS `userId`,
		`ForumComment`.`comment` AS `comment`,
		`ForumComment`.`createDate` AS `createDate`
	FROM `ForumComment`
	WHERE 		`ForumComment`.`id` = paramid;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_LoadAll`
()
BEGIN
	SELECT
		`ForumComment`.`id` AS `id`,
		`ForumComment`.`forumId` AS `forumId`,
		`ForumComment`.`userId` AS `userId`,
		`ForumComment`.`comment` AS `comment`,
		`ForumComment`.`createDate` AS `createDate`
	FROM `ForumComment`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_Add`
(
	 IN paramforumId INT,
	 IN paramuserId INT,
	 IN paramcomment VARCHAR(32768),
	 IN paramcreateDate DATETIME
)
BEGIN
	INSERT INTO `ForumComment` (forumId,userId,comment,createDate)
	VALUES (paramforumId, paramuserId, paramcomment, paramcreateDate);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_Update`
(
	IN paramid INT,
	IN paramforumId INT,
	IN paramuserId INT,
	IN paramcomment VARCHAR(32768),
	IN paramcreateDate DATETIME
)
BEGIN
	UPDATE `ForumComment`
	SET forumId = paramforumId
		,userId = paramuserId
		,comment = paramcomment
		,createDate = paramcreateDate
	WHERE		`ForumComment`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_Delete`
(
	IN paramid INT
)
BEGIN
	DELETE FROM `ForumComment`
	WHERE		`ForumComment`.`id` = paramid;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_ForumComment_Search`
(
	IN paramid INT,
	IN paramforumId INT,
	IN paramuserId INT,
	IN paramcomment VARCHAR(32768),
	IN paramcreateDate DATETIME
)
BEGIN
	SELECT
		`ForumComment`.`id` AS `id`,
		`ForumComment`.`forumId` AS `forumId`,
		`ForumComment`.`userId` AS `userId`,
		`ForumComment`.`comment` AS `comment`,
		`ForumComment`.`createDate` AS `createDate`
	FROM `ForumComment`
	WHERE
		COALESCE(ForumComment.`id`,0) = COALESCE(paramid,ForumComment.`id`,0)
		AND COALESCE(ForumComment.`forumId`,0) = COALESCE(paramforumId,ForumComment.`forumId`,0)
		AND COALESCE(ForumComment.`userId`,0) = COALESCE(paramuserId,ForumComment.`userId`,0)
		AND COALESCE(ForumComment.`comment`,'') = COALESCE(paramcomment,ForumComment.`comment`,'')
		AND COALESCE(CAST(ForumComment.`createDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramcreateDate AS DATE),CAST(ForumComment.`createDate` AS DATE), CAST(NOW() AS DATE));
END //
DELIMITER ;


