/*
Author:			This code was generated by DALGen version 1.0.0.0 available at https://github.com/H0r53/DALGen 
Date:			10/15/2017
Description:	Creates the Permission table and respective stored procedures

*/


USE opendevtools;



-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `opendevtools`.`Permission` (
Id INT AUTO_INCREMENT,
name VARCHAR(255),
description VARCHAR(1047),
createDate DATETIME,
CONSTRAINT pk_Permission_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`Permission`.`Id` AS `Id`,
		`Permission`.`name` AS `name`,
		`Permission`.`description` AS `description`,
		`Permission`.`createDate` AS `createDate`
	FROM `Permission`
	WHERE 		`Permission`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_LoadAll`()
BEGIN
	SELECT
		`Permission`.`Id` AS `Id`,
		`Permission`.`name` AS `name`,
		`Permission`.`description` AS `description`,
		`Permission`.`createDate` AS `createDate`
	FROM `Permission`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_Add`
(
	 IN paramname VARCHAR(255),
	 IN paramdescription VARCHAR(1047),
	 IN paramcreateDate DATETIME
)
BEGIN
	INSERT INTO `Permission` (name,description,createDate)
	VALUES (paramname, paramdescription, paramcreateDate);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_Update`
(
	IN paramId INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(1047),
	IN paramcreateDate DATETIME
)
BEGIN
	UPDATE `Permission`
	SET name = paramname
		,description = paramdescription
		,createDate = paramcreateDate
	WHERE		`Permission`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `Permission`
	WHERE		`Permission`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `opendevtools`.`usp_Permission_Search`
(
	IN paramId INT,
	IN paramname VARCHAR(255),
	IN paramdescription VARCHAR(1047),
	IN paramcreateDate DATETIME
)
BEGIN
	SELECT
		`Permission`.`Id` AS `Id`,
		`Permission`.`name` AS `name`,
		`Permission`.`description` AS `description`,
		`Permission`.`createDate` AS `createDate`
	FROM `Permission`
	WHERE
		COALESCE(Permission.`Id`,0) = COALESCE(paramId,Permission.`Id`,0)
		AND COALESCE(Permission.`name`,'') = COALESCE(paramname,Permission.`name`,'')
		AND COALESCE(Permission.`description`,'') = COALESCE(paramdescription,Permission.`description`,'')
		AND COALESCE(CAST(Permission.`createDate` AS DATE), CAST(NOW() AS DATE)) = COALESCE(CAST(paramcreateDate AS DATE),CAST(Permission.`createDate` AS DATE), CAST(NOW() AS DATE));
END //
DELIMITER ;


